### ISSUE TITLE
Keep prefixing output with `/usr/local/src/your-app/`

### ISSUE THREAD

**Issue by bentcoder** [github-changelog-generator/docker-github-changelog-generator#23]
Hi,

When using `-o` flag, the output location is being prefixed with `/usr/local/src/your-app/`.

Thanks

**Command**

```bash
docker run -it --rm -v "$(pwd)":"$(pwd)" ferrarimarco/github-changelog-generator github_changelog_generator -u myself -p my-project -t my-token -o /my/path/to/app/CHANGELOG.md
```

**Output**

```bash
Using these options:
:date_format=>"%Y-%m-%d"
:output=>"/my/path/to/app/CHANGELOG.md"
...
...
Done!
Generated log placed in /usr/local/src/your-app//my/path/to/app/CHANGELOG.md
```

**Comment by ferrarimarco** [comment]
Hi @BentCoder !

What's exactly the issue? :)

**Comment by bentcoder** [comment]
This is the output I define: `-o /my/path/to/app/CHANGELOG.md`
This is what command reports: `:output=>"/my/path/to/app/CHANGELOG.md"`

But this is where it says it will generate the output: `Generated log placed in /usr/local/src/your-app//my/path/to/app/CHANGELOG.md`

Instead I would expect to see: `Generated log placed in /my/path/to/app/CHANGELOG.md`

**Comment by juliek-tmf** [comment]
To anyone who finds themselves here - this confused me too. Changing the `-o` parameter just changes where the file is dropped inside the container (see the [Dockerfile](https://github.com/github-changelog-generator/docker-github-changelog-generator/blob/master/Dockerfile)). The way to control the output path is to either move to a new `pwd` (easiest) or mount the container-side `/usr/local/src/your-app` to another local directory by replacing `$(pwd)` in the `docker run` command (also very doable).

I really appreciate having the docker option for this helpful tool! So much better than maintaining Ruby and installing gems. Thank you @ferrarimarco 😄

**Comment by anthosz** [comment]
+1

**Comment by piq9117** [comment]
This is my script
```shell
docker run -it --rm -v "$(pwd)":$GITROOT \
	-e CHANGELOG_GITHUB_TOKEN=$CHANGELOG_GITHUB_TOKEN \
	githubchangeloggenerator/github-changelog-generator -u <username> -p <project-name> -o $GITROOT/CHANGELOG.md
```
encountered the same output log as @bentcoder lol
```
Generated log placed in /usr/local/src/your-app//my/path/to/app/CHANGELOG.md
```
