### ISSUE TITLE
Github Changelog Generator should be upgraded to 1.15.pre.beta

### ISSUE THREAD

**Issue by markmandel** [github-changelog-generator/docker-github-changelog-generator#3]
Seeing some issues with 1.14 - would love an image of v1.15 beta that would be awesome, even if it's just to take it for a spin.

https://github.com/github-changelog-generator/github-changelog-generator/releases/tag/v1.15.0.pre.beta

Thanks for making this image!

**Comment by ferrarimarco** [comment]
There is a pre.rc version as well. Any reason to stick with the pre.beta?

**Comment by ferrarimarco** [comment]
Update: I've pushed `1.15.pre.alpha`, `1.15.pre.beta`, `1.15.pre.rc`
