### ISSUE TITLE
Docker image for github-changelog-generator version 1.15.2

### ISSUE THREAD

**Issue by renehernandez** [github-changelog-generator/docker-github-changelog-generator#32]
Currently the latest docker image is 1.15.0 while the github-changelog-generator project is up to 1.15.2

I am looking forward to use some of the latest improvements/fixes through github actions, but the latest version is not released yet as docker image

**Comment by ferrarimarco** [comment]
Correct! We do have a PR opened by dependabot. Let me have a look at that...

**Comment by ferrarimarco** [comment]
Released the 1.15.2 tag. Docker hub wasn't picking up the latest changes for some reason :)
