### ISSUE TITLE
ferrarimarco/github-changelog-generator AArch64 support

### ISSUE THREAD

**Issue by odidev** [github-changelog-generator/docker-github-changelog-generator#33]
Summary
AArch64 support for ferrarimarco/github-changelog-generator.

Problem description
ferrarimarco/github-changelog-generator doesn't support AArch64. Enabling it for AArch64 will lead to a better experience for arm64 users. 

Expected Output
ferrarimarco/github-changelog-generator should run on AArch64.

@team, please let me know if I can help you making it available for aarch64. It will be a great opportunity for me to work with you.

**Comment by ferrarimarco** [comment]
Hi @odidev ! Feel free to open a PR for this :)

**Comment by mpmkp2020** [comment]
@ferrarimarco thanks for the quick response, I am working on it. Thanks.

**Comment by odidev** [comment]
@ferrarimarco thanks for the quick response, I am working on it. Thanks.

**Comment by odidev** [comment]
Raised PR: https://github.com/github-changelog-generator/docker-github-changelog-generator/pull/34. Please have a look at this.

**Comment by ferrarimarco** [comment]
Multi-architecture builds are now available, including arm64. :)
